version: '3'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./data/zoo1/data:/data
      - ./data/zoo1/datalog:/datalog
    # networks:
    #   - frontend

  kafka1:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${IP_KAFKA:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,state.change.logger=WARN"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
    # networks:
    #   - frontend

  # rproxy:
  #   hostname: rproxy
  #   image: mattes/rotating-proxy
  #   deploy:
  #     placement:
  #       constraints: [node.role == worker]
  #   environment:
  #     - tors=25
  #   logging:
  #     driver: none
  #   ports:
  #     - "5566:5566"
  #     - "4444:4444"
  #   networks:
  #     - frontend

  mongo:
    hostname: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - "27018:27017"
    volumes:
      - ./data/mongo:/data/db

  producer:
    image: adrz/producer
    environment:
      IP_KAFKA: kafka1
      PORT_KAFKA: 19092
      TOPIC: twitch
      TOPIC_SUB: streams
    build:
      context: ./producer
    entrypoint:
      - python
      - app.py
    volumes:
      - ./data/audios:/app/audios
      - ./producer:/app
    # deploy:
    #   replicas: 2
    depends_on:
      - kafka1
    links:
      - kafka1
    # networks:
    #   - frontend

  orchestrator:
    image: adrz/orchestrator
    environment:
      IP_KAFKA: kafka1
      PORT_KAFKA: 19092
      TOPIC_SUB: streams
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_USER: root
      INFLUXDB_PASS: root
      INFLUXDB_DB: twitch
      INFLUXDB_MEASUREMENT: twitch_transcript
    ports:
      - "8080:5000"
    build:
      context: ./producers_orchestrator
    entrypoint:
      - python
      - app.py
    depends_on:
      - kafka1
      - influxdb
    links:
      - kafka1
    # networks:
    #   - frontend

  consumer:
    image: adrz/consumer
    environment:
      IP_KAFKA: kafka1
      PORT_KAFKA: 19092
      TOPIC: twitch
      PROXY: rproxy:5566
      MONGODB_HOST: mongo:27017
      MONGODB_DB: twitch
      MONGODB_COLLECTION: speech2text
      N_THREADS: 10
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_USER: root
      INFLUXDB_PASS: root
      INFLUXDB_DB: twitch
      INFLUXDB_MEASUREMENT: twitch_transcript
    build:
      context: ./consumer
    volumes:
      - ./data/audios/curses:/app/audios/curses
      - ./data/audios/voice:/app/audios/voice
      - ./data/audios/novoice:/app/audios/novoice
    entrypoint:
      - python
      - main.py
    # deploy:
    #   replicas: 3
    depends_on:
      - kafka1
      - mongo
    links:
      - kafka1
      - mongo
      - influxdb
      # - rproxy
    # networks:
    #   - frontend

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./data/influxdb/config:/etc/influxdb
      - ./data/influxdbroot/:/root/.influxdb
    ports:
      - "8086:8086"
      - "8082:8082"

# networks:
#   frontend:
#     driver: overlay
